[workspace]
members = ["packages/toak-rs", "packages/toak-ocr"]
resolver = "2"

[workspace.package]
version = "6.0.0"
authors = ["Geoff Seemueller"]
edition = "2021"
repository = "https://github.com/geoffsee/toak"
license = "AGPL-3.0-or-later"
